In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [2]:
iris = pd.read_csv('iris_dataset.csv')
iris.head()

SepalLength  SepalWidth  PetalLength  PetalWidth    Name
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [11]:
iris['Name'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [13]:
iris['Name'] = iris['Name'].map({'setosa':0, 'versicolor':1, 'virginica':2})

In [14]:
X = iris.iloc[:,0:4]
T = iris['Name']

In [17]:
T = np_utils.to_categorical(T)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [18]:
T[:3]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [19]:
np.random.seed(0)

In [20]:
train_x, test_x, train_t, test_t = train_test_split(X, T, test_size=0.3, stratify=T)

In [32]:
model = Sequential()
model.add(Dense(input_dim=4, units=3))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.1))
model.fit(train_x, train_t, epochs=10, batch_size=10)

Epoch 1/10
11/11 [==============================] - 0s 1ms/step - loss: 2.4277
Epoch 2/10
11/11 [==============================] - 0s 2ms/step - loss: 0.8480
Epoch 3/10
11/11 [==============================] - 0s 1ms/step - loss: 0.7281
Epoch 4/10
11/11 [==============================] - 0s 2ms/step - loss: 0.8131
Epoch 5/10
11/11 [==============================] - 0s 2ms/step - loss: 0.8922
Epoch 6/10
11/11 [==============================] - 0s 1ms/step - loss: 0.5637
Epoch 7/10
11/11 [==============================] - 0s 1ms/step - loss: 0.8903
Epoch 8/10
11/11 [==============================] - 0s 1ms/step - loss: 0.6011
Epoch 9/10
11/11 [==============================] - 0s 2ms/step - loss: 0.6146
Epoch 10/10
11/11 [==============================] - 0s 1ms/step - loss: 0.3969


In [33]:
Y = model.predict_classes(test_x, batch_size=10)
Y[:3]

/home/user/.pyenv/versions/3.7.8/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([0, 0, 2])

In [30]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
_________________________________________________________________
activation (Activation)      (None, 3)                 0         
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [31]:
model.get_weights()

[array([[ 0.5455712 ,  0.5321702 , -1.6545686 ],
        [ 1.6896442 , -0.36000454, -1.808985  ],
        [-2.951444  , -0.8415919 ,  2.2129116 ],
        [-0.7189292 , -0.3347796 ,  2.2785623 ]], dtype=float32),
 array([ 0.42699456,  0.44294962, -0.86994374], dtype=float32)]

In [25]:
_, T_index = np.where(test_t > 0)

In [26]:
T_index[:3]

array([0, 0, 2])

In [27]:
from sklearn.metrics import accuracy_score

In [34]:
score = accuracy_score(Y, T_index)
print(score)

0.6666666666666666
