In [1]:
from sklearn import datasets
import numpy as np
import pandas as pd

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from keras.utils import np_utils

In [2]:
iris = datasets.load_iris()

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [14]:
data = iris.data
target = iris.target

In [16]:
np.random.seed(0)

In [18]:
X = data
T = np_utils.to_categorical(target)

In [20]:
T[:3]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [21]:
train_x, test_x, train_t, test_t = train_test_split(X, T, test_size=0.2, stratify=T)

In [22]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [24]:
model = Sequential()
model.add(Dense(input_dim=4, units=5, activation='relu'))
model.add(Dense(units=3, activation='softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 5)                 25        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 18        
Total params: 43
Trainable params: 43
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.1))

In [26]:
model.fit(train_x, train_t, epochs=100, batch_size=5)

Epoch 1/100
24/24 [==============================] - 0s 611us/step - loss: 1.0938
Epoch 2/100
24/24 [==============================] - 0s 1ms/step - loss: 0.7261
Epoch 3/100
24/24 [==============================] - 0s 659us/step - loss: 0.6390
Epoch 4/100
24/24 [==============================] - 0s 778us/step - loss: 0.5845
Epoch 5/100
24/24 [==============================] - 0s 800us/step - loss: 0.5369
Epoch 6/100
24/24 [==============================] - 0s 648us/step - loss: 0.5225
Epoch 7/100
24/24 [==============================] - 0s 645us/step - loss: 0.4785
Epoch 8/100
24/24 [==============================] - 0s 644us/step - loss: 0.4592
Epoch 9/100
24/24 [==============================] - 0s 653us/step - loss: 0.4366
Epoch 10/100
24/24 [==============================] - 0s 686us/step - loss: 0.4364
Epoch 11/100
24/24 [==============================] - 0s 579us/step - loss: 0.4497
Epoch 12/100
24/24 [==============================] - 0s 637us/step - loss: 0.4009
Epoch 13/100
24

24/24 [==============================] - 0s 615us/step - loss: 0.2203
Epoch 100/100
24/24 [==============================] - 0s 597us/step - loss: 0.1804


In [28]:
Y = model.predict_classes(test_x)

In [29]:
Y

array([2, 1, 2, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 2, 2, 0,
       0, 0, 2, 1, 1, 0, 2, 2])

In [33]:
_, T_index = np.where(test_t>0)

In [34]:
score = accuracy_score(Y, T_index)
print(score)

1.0


In [44]:
np.argmax(model.predict(test_x), axis=1)

array([2, 1, 2, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 2, 2, 0,
       0, 0, 2, 1, 1, 0, 2, 2])

In [41]:
model.predict(test_x)

array([[1.86520746e-22, 1.03614153e-03, 9.98963833e-01],
       [5.86379212e-09, 6.95123196e-01, 3.04876715e-01],
       [4.21987289e-23, 7.27088016e-04, 9.99272883e-01],
       [9.57979977e-01, 4.19996046e-02, 2.04754215e-05],
       [3.36695696e-17, 1.83365792e-02, 9.81663346e-01],
       [9.02750497e-09, 7.20712304e-01, 2.79287726e-01],
       [9.57979977e-01, 4.19996046e-02, 2.04754215e-05],
       [1.36702740e-16, 2.54707821e-02, 9.74529207e-01],
       [1.39040365e-18, 8.63897428e-03, 9.91361082e-01],
       [5.89041330e-04, 9.86317098e-01, 1.30938897e-02],
       [9.57979977e-01, 4.19996046e-02, 2.04754215e-05],
       [2.30138130e-06, 9.31065917e-01, 6.89317361e-02],
       [8.03405964e-09, 7.13910341e-01, 2.86089689e-01],
       [9.57979977e-01, 4.19996046e-02, 2.04754215e-05],
       [1.77522306e-04, 9.80896115e-01, 1.89263895e-02],
       [9.57979977e-01, 4.19996046e-02, 2.04754215e-05],
       [9.57979977e-01, 4.19996046e-02, 2.04754215e-05],
       [1.68377974e-05, 9.61432

In [42]:
model.predict(test_x).shape

(30, 3)