In [15]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD,Adam
from tensorflow.keras.utils import to_categorical

In [2]:
X = np.load('./mnist_data.npz')
T = np.load('./mnist_target.npz')

In [4]:
X = X['arr_0']
T = T['arr_0']

In [5]:
X_train, X_test, T_train, T_test = train_test_split(X, T, test_size=0.3, stratify=T, random_state=1)

In [9]:
T_train.shape

(49000,)

In [10]:
X_train.shape

(49000, 784)

In [11]:
T_train_categorical = to_categorical(T_train)

In [12]:
T_train_categorical

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [13]:
T_train_categorical.shape

(49000, 10)

In [18]:
model = Sequential()
model.add(Dense(input_dim=784, units=2000, activation='sigmoid'))
model.add(Dense(units=10, activation='softmax'))
model.compile(loss='categorical_crossentropy', metrics='accuracy', optimizer=SGD(lr=0.01))

In [19]:
result = model.fit(X_train, T_train_categorical, epochs=50, batch_size=2048)

Epoch 1/50
24/24 [==============================] - 3s 98ms/step - loss: 1.8792 - accuracy: 0.4030
Epoch 2/50
24/24 [==============================] - 2s 98ms/step - loss: 0.8662 - accuracy: 0.8005
Epoch 3/50
24/24 [==============================] - 3s 107ms/step - loss: 0.6395 - accuracy: 0.8530
Epoch 4/50
24/24 [==============================] - 2s 103ms/step - loss: 0.5378 - accuracy: 0.8729
Epoch 5/50
24/24 [==============================] - 3s 105ms/step - loss: 0.4759 - accuracy: 0.8882
Epoch 6/50
24/24 [==============================] - 3s 105ms/step - loss: 0.4337 - accuracy: 0.8969
Epoch 7/50
24/24 [==============================] - 3s 108ms/step - loss: 0.4069 - accuracy: 0.9016
Epoch 8/50
24/24 [==============================] - 3s 108ms/step - loss: 0.3774 - accuracy: 0.9101
Epoch 9/50
24/24 [==============================] - 3s 111ms/step - loss: 0.3595 - accuracy: 0.9136
Epoch 10/50
24/24 [==============================] - 3s 113ms/step - loss: 0.3505 - accuracy: 0.9132
E

In [26]:
Y = model.predict(X_test)

In [29]:
Y

array([[1.52302533e-01, 4.80275281e-04, 6.09685958e-04, ...,
        2.67367018e-03, 4.51271571e-02, 5.87715360e-04],
       [3.74705088e-03, 1.44235848e-04, 5.80261039e-05, ...,
        3.59948346e-04, 3.31798289e-03, 7.51927262e-04],
       [3.85159743e-03, 1.66881233e-02, 1.37822982e-02, ...,
        9.94801521e-02, 1.61492899e-01, 4.85246807e-01],
       ...,
       [8.69743340e-03, 1.45162921e-03, 1.79429054e-01, ...,
        5.27679440e-05, 7.44910969e-04, 4.63412507e-05],
       [2.01323332e-04, 1.18519438e-05, 9.99192417e-01, ...,
        7.91683703e-07, 8.70356453e-05, 2.71775207e-06],
       [1.55302296e-05, 1.00152665e-05, 6.34006923e-04, ...,
        2.24087373e-04, 3.00386397e-04, 2.13214196e-03]], dtype=float32)

In [22]:
np.argmax(Y, axis=-1)

array([5, 5, 9, ..., 6, 2, 4])

In [23]:
Y = np.argmax(Y, axis=-1)

In [24]:
score = accuracy_score(Y, T_test)

In [25]:
score

0.9301428571428572

In [30]:
T_test_onehot = to_categorical(T_test)
loss, accuracy = model.evaluate(X_test, T_test_onehot)

657/657 [==============================] - 3s 4ms/step - loss: 0.2464 - accuracy: 0.9301
